[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["service_chaining_sample"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "service_chaining_sample"
  org = "wso2sa"
  version = "3.1.1"

